I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/spe/donnees_perso/situation_spe.rpy", line 1, in script
    init python:
  File "game/spe/donnees_perso/situation_spe.rpy", line 1, in script
    init python:
  File "game/spe/donnees_perso/situation_spe.rpy", line 7, in <module>
    from chapitres.templiers import carac
ImportError: No module named chapitres.templiers

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/spe/donnees_perso/situation_spe.rpy", line 1, in script
    init python:
  File "game/spe/donnees_perso/situation_spe.rpy", line 1, in script
    init python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/spe/donnees_perso/situation_spe.rpy", line 7, in <module>
    from chapitres.templiers import carac
ImportError: No module named chapitres.templiers

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
L'épée du samouraï 1.0
Wed Jun 29 21:39:58 2022
